//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cellent.Template.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cellent.Template.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &apos;{0}&apos; darf nicht leer sein..
        /// </summary>
        internal static string FieldCannotBeNotNull {
            get {
                return ResourceManager.GetString("FieldCannotBeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld &apos;{0}&apos; ist nicht nummerisch..
        /// </summary>
        internal static string IsNotNummeric {
            get {
                return ResourceManager.GetString("IsNotNummeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die maximale Länge ({0}) des Feldes &apos;{1}&apos; wurde überschritten..
        /// </summary>
        internal static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die minimale Länge ({0}) des Feldes &apos;{1}&apos; wurde unterschritten..
        /// </summary>
        internal static string MinLengthFallenBelow {
            get {
                return ResourceManager.GetString("MinLengthFallenBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe für Feld &apos;{0}&apos;..
        /// </summary>
        internal static string NoValidDate {
            get {
                return ResourceManager.GetString("NoValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feld &apos;{0}&apos; ist keine gültige Emailadresse..
        /// </summary>
        internal static string NoValidEmail {
            get {
                return ResourceManager.GetString("NoValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Feld &apos;{0}&apos; muss gleich ({1}) sein..
        /// </summary>
        internal static string NumberValidatorEqual {
            get {
                return ResourceManager.GetString("NumberValidatorEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Feld &apos;{0}&apos; muss groesser als ({1}) sein..
        /// </summary>
        internal static string NumberValidatorGreater {
            get {
                return ResourceManager.GetString("NumberValidatorGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Feld &apos;{0}&apos; muss groessergleich ({1}) sein..
        /// </summary>
        internal static string NumberValidatorGreaterEqual {
            get {
                return ResourceManager.GetString("NumberValidatorGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Feld &apos;{0}&apos; muss kleiner als ({1}) sein..
        /// </summary>
        internal static string NumberValidatorLess {
            get {
                return ResourceManager.GetString("NumberValidatorLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe für Feld &apos;{0}&apos; muss kleinergleich ({1}) sein..
        /// </summary>
        internal static string NumberValidatorLessEqual {
            get {
                return ResourceManager.GetString("NumberValidatorLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe für Feld &apos;{0}&apos;..
        /// </summary>
        internal static string RegexValidator {
            get {
                return ResourceManager.GetString("RegexValidator", resourceCulture);
            }
        }
    }
}
